"""empty message

Revision ID: 84a980c3e4a5
Revises: 0218a9383666
Create Date: 2020-01-30 20:22:00.499881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84a980c3e4a5'
down_revision = '0218a9383666'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Artist', 'seeking_description',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('Artist', 'seeking_venue',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.drop_column('Shows', 'id')
    op.alter_column('Venue', 'seeking_description',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('Venue', 'website',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Venue', 'website',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('Venue', 'seeking_description',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.add_column('Shows', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('Artist', 'seeking_venue',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('Artist', 'seeking_description',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    # ### end Alembic commands ###
