"""empty message

Revision ID: a12fb843e220
Revises: 84a980c3e4a5
Create Date: 2020-02-02 14:56:42.795023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a12fb843e220'
down_revision = '84a980c3e4a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Artist', 'website',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('Shows', sa.Column('artist_id', sa.Integer(), nullable=False))
    op.add_column('Shows', sa.Column('venue_id', sa.Integer(), nullable=False))
    op.drop_constraint('Shows_Venue_id_fkey', 'Shows', type_='foreignkey')
    op.drop_constraint('Shows_Artist_id_fkey', 'Shows', type_='foreignkey')
    op.create_foreign_key(None, 'Shows', 'Artist', ['artist_id'], ['id'])
    op.create_foreign_key(None, 'Shows', 'Venue', ['venue_id'], ['id'])
    op.drop_column('Shows', 'Artist_id')
    op.drop_column('Shows', 'Venue_id')
    op.alter_column('Venue', 'seeking_description',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('Venue', 'website',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Venue', 'website',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('Venue', 'seeking_description',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.add_column('Shows', sa.Column('Venue_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('Shows', sa.Column('Artist_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'Shows', type_='foreignkey')
    op.drop_constraint(None, 'Shows', type_='foreignkey')
    op.create_foreign_key('Shows_Artist_id_fkey', 'Shows', 'Artist', ['Artist_id'], ['id'])
    op.create_foreign_key('Shows_Venue_id_fkey', 'Shows', 'Venue', ['Venue_id'], ['id'])
    op.drop_column('Shows', 'venue_id')
    op.drop_column('Shows', 'artist_id')
    op.alter_column('Artist', 'website',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
